### ISSUE TITLE
Handle Deeply Nested Extensions

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-fhir-export#10]
In some cases, a field's sub-field may be mapped to something in the FHIR target, but the field's other sub-fields are not.  In this case we (probably) shouldn't create a stand-alone extension for the whole field (since _part_ of it is already mapped) -- but we need to do something with the other sub-fields.  Those will likely be extensions, but not necessarily at the root of the resource.

We need to determine how we want to handle this -- what we do with unmapped sub-fields and where we put them.

**Comment by markkramerus** [comment]
It might be possible to disambiguate by adding something to the mapping grammar, e.g., map <shr-path> as extension to <fhir-path> or something like that.

**Comment by markkramerus** [comment]
It's been implemented as "maps to [path].extension
