### ISSUE TITLE
Improve Ability To Create Other IGs

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-fhir-export#11]
The exporter currently supports just an SHR IG -- with many aspects of that hard-coded in.  3rd parties may wish to create their own IGs using SHR as a base, in which they would want to define their own index page and only include those SHR profiles/extensions/terminologies referenced by _their_ profiles.  This would require modularizing the export more than it currently is.

**Comment by markkramerus** [comment]
OBE
