### ISSUE TITLE
Broken icons

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#127]
Can we fix the broken icons (see png)? Looks like a trivial fix
<img width="111" alt="BrokenIcons" src="https://user-images.githubusercontent.com/492232/54680208-ac46e300-4adf-11e9-897d-67e71628f627.PNG">

**Comment by cmoesel** [comment]
That is an IG Publisher issue.  I'm not sure how much we can easily do, but we can look into it.

The first thing I'll probably try is updating us to the latest IG Publisher.

**Comment by markkramerus** [comment]
The missing files are three: tbl_vjoin_slice.png, tbl_vline_slice.png, and tbl_vjoin_end_slice.png

**Comment by markkramerus** [comment]
Fixed some time ago. Closing.
