### ISSUE TITLE
Pages Generate Without Titles

### ISSUE THREAD

**Issue by Dtphelan1** [standardhealth/shr-fhir-export#22]
All of the pages generate with an empty title tag `<title></title>`, which causes display issues especially with the redirection work-around we figured out for the cannonical links to pages.

**Comment by cmoesel** [comment]
I think this is fixed in the latest version (for FHIR 3.0).  Have you tried it with the code currently in master?

**Comment by Dtphelan1** [comment]
I thought I did, but I could be wrong on that. 

Let me get back to you on that front.

**Comment by cmoesel** [comment]
Confirmed to be working on master.
