### ISSUE TITLE
SHR Formal Definition produces substandard link

### ISSUE THREAD

**Issue by Dtphelan1** [standardhealth/shr-fhir-export#23]
From Chris: "For example, go to: https://dtphelan1.github.io/fhir/StructureDefinition-shr-actor-EmergencyContact.html

Scroll down to where it says “SHR Formal Definition” and click the “EmergencyContact” link there.  You’ll see it does to the MD/HTML representation instead of the SSVE representation." 

We should discuss whether, long term, this is an IG issue or an SHR.org issue. I understand if that's a canonical link, and should always point to the appropriate location; but right now the link points to a location other than the canonical one, though it's not the SHR.org standard location. So should this link just continue pointing to the non-canonical-but-shr-appropriate location, or should there be some sort of redirect that happens when you visit the canonical location?

**Comment by markkramerus** [comment]
OBE. The relationships between the HTML _page_ and the formal _URL_ is handled by the IG Publisher and configuration parameters.
