### ISSUE TITLE
Change mapping grammar to refer to options consistently

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#31]
We currently have (for example):  OccurrenceTime[date] maps to start[x].Date

I would prefer it to be:  OccurrenceTime[date] maps to start[Date]  -- without the [x]. That would simplify the mapping grammar.

**Comment by Abhijay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change mapping grammar to refer to options consistently](https://trello.com/c/gClGthgu/5-change-mapping-grammar-to-refer-to-options-consistently)

**Comment by markkramerus** [comment]
Added this suggestion to https://jira.mitre.org/browse/SHRO-545.
