### ISSUE TITLE
Constrain to fixed value

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#32]
We need a way to constrain an element to a fixed value on the FHIR side

Example: Constrain Careplan.intent to #plan (because it's a care PLAN, for Pete's sake)

**Comment by cmoesel** [comment]
This was added (for codes only) in the latest beta release.  The grammar is similar to (but slightly different than) the example above.  For example, in the Observation mapping, we now have:
```
fix related.type to #has-member
```
