### ISSUE TITLE
Profile missing attribute name and description when mapping Value [High Priority]

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#33]
In the generated profiles, I'm not seeing the correct descriptive names on extensions. For example, in the shr-oncology-N-Stage profile, in the Differential, I see this in the implementation guide (columns presented as rows for clarity):

       Name:  shr-core-CodeableConcept-extension  
       Card:   1..1
       Type:   SHR CodeableConcept Profile
       Description & Constraints:  SHR CodeableConcept Extension

From that information, the user has no idea which element this is supposed to be, except it is a CodeableConcept.  There has got to be an attribute name and definition.  I believe it should be something more like this:

       Name:  shr-oncology-N-Stage-value-extension
       Card:   1..1
       Type:   SHR CodeableConcept Profile
       Description & Constraints:  The presence of metastases in regional lymph nodes. TNM node category for staging derived from the American Joint Committee on Cancer. See Table 147 in HL7 CDA® R2 Implementation Guide: Clinical Oncology Treatment Plan and Summary, Release 1 - US Realm

**Comment by markkramerus** [comment]
Investigating the example, this is the Value attribute, so the attribute name should be "N-Stage" (the name of the element) and the description should come from the **Description** field of the element. It's a special case, but very common, and needs to be fixed.

**Comment by cmoesel** [comment]
Cannot reproduce.  In the example above, the value shouldn't be an extension in the first place -- it should be mapped to `value[x]`.  Using the grammar 5 tooling and onco_2 branch of SHR, the value appears to be properly restricting `value[x]` to an SHR CodeableConcept -- and not an extension. Reporter also confirmed that he can no longer reproduce it either.
