### ISSUE TITLE
"If covered" binding lost between SHR and IG [Medium Priority]

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#37]
The "if covered" in SHR is not converted into an extensible binding in the resulting IG. For example, in Observation: 

0..*			Category from ObservationCategoryVS if covered

In the IG, it appears as:  SHR BRCA1Variant Profile

category   SHR CodeableConcept Profile   Binding: SHR ObservationCategoryVS ValueSet **(required)**

Seems to happen for all "if covered" statements

**Comment by cmoesel** [comment]
I've found the issue -- it was in the shr-text-importer.  If you used the keywords "must be from", then the "if covered" was properly honored.  But if you just said "from" (without "must be") then "if covered" was ignored.

This is fixed locally and will go into the next shr-text-import release.

**Comment by cmoesel** [comment]
Fixed in shr-fhir-export v5.0.0-beta.4 and shr-cli v5.0.0-beta.5.
