### ISSUE TITLE
String value constraint on Observation generating spurious Warning [Low Priority]

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#41]
Element:		ReligiousCongregation
		Concept:		TBD
		Based on:	Observation
		Description:	"A group of place of religious practice."
		Value:		string  // This is generating a warning, not sure why

12:02:15.744Z]  WARN shr: The 'value[x]' property is not bound to a value set, fixed to a code, or fixed to a quantity unit. This property is core to the target resource and usually should be constrained. (module=shr-fhir-export, shrId=shr.behavior.ReligiousCongregation, target=Observation)

**Comment by cmoesel** [comment]
Agreed.  That should not be happening.  We will take a look.

**Comment by Abhijay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [String value constraint on Observation generating warning](https://trello.com/c/Wwdh1Qkd/4-string-value-constraint-on-observation-generating-warning)

**Comment by Abhijay** [comment]
(For proper bookkeeping)

(Tentatively) resolved by commits:
https://github.com/standardhealth/shr-fhir-export/commit/09f1ea0357d52a199343a9ad60a056aa3afafcad

> Previously a warning was raised when the value of an object based on Observation was a primitive.
> 
> There previously was no check for a value of a primitive, so I added one. However, I'm not too familiar with what's supposed to be happening in this space, so I'm marking this as a tentative solution that needs review.


Needs approval by @cmoesel

**Comment by cmoesel** [comment]
I discovered the root of the problem and think I've fixed it (the previous fix addressed the symptom more than the problem).  Note that this fix also resulted in an "improvement" that detected some unconstrained elements that were passing by undetected before (oops).  So, there are more warnings now (sorry), but they are legit.

Addressed in commit 8536e22, which I've asked Abhijay to review.

**Comment by cmoesel** [comment]
Fixed in SHR CLI 5.0.0 Beta 8.
