### ISSUE TITLE
Suppress individual warning messages [Feature Request]

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#42]
I would like a way to suppress individual warning messages, those that I've seen before, and for whatever reason, were not/will not be addressed.  Why? Because each time I see that message again, it takes some time to mentally process it and remember that was something that can be dismissed "Oh, I've seen that one before - never mind."
How to do it? Not sure, but here are two possibilities
1) Put a "ignore" tag in the source SHR file (this is what I'm doing now, just to remind myself that I've looked at an issue previously)
2) Have a filtering file where ignorable messages can be stored (can we hash code each message to uniquely identify it???)

**Comment by cmoesel** [comment]
We've discussed that each type of possible error message should have a unique identifier or key.  If we had that, then I think we could easily create a file that indicates warnings to suppress.  For example, one line might looking something like:
```
shr.core.Duration: PARENT_MAPPING_MISMATCH
```

Putting comments in the source itself is also a valid approach, although I wonder if that would start to look cluttered.

**Comment by markkramerus** [comment]
This is being worked by Gary, and well on its way to completion. Closing this feature request.
