### ISSUE TITLE
Fix booleans to true or false

### ISSUE THREAD

**Issue by markkramerus** [standardhealth/shr-fhir-export#69]
Error message says it all:

ERROR shr: Currently, only fixing codes is supported (value must contain "#").  Unable to fix to false. ERROR_CODE:13016 (module=shr-fhir-export, shrId=shr.immunization.ImmunizationGiven, mappingRule="fix notGiven to false\r")

**Comment by cmoesel** [comment]
This is fixed in shr-cli 5.3.3.
