### ISSUE TITLE
Mapping Fixed Concept sub-fields does not work

### ISSUE THREAD

**Issue by cmoesel** [standardhealth/shr-fhir-export#82]
May not be a big deal, but if we have an element like this:
```
Element: Foo
1..1 SomeConceptValue is FOO#bar
```
Then mapping the whole concept works and properly fixes the whole code in FHIR:
```
SomeConceptValue.CodeableConcept maps to code
```
But this does not properly fix just the system in FHIR (it does nothing):
```
SomeConceptValue.CodeableConcept.Coding.CodeSystem maps to code.coding.system
```

**Comment by cmoesel** [comment]
I only say its not a big deal because there probably isn't a very meaningful use case for it.

**Comment by markkramerus** [comment]
Overcome by events. Concept has replaced CodeableConcept, Coding, code.
